----1
select DEPARTMENT_NAME "학과 명", CATEGORY 계열
FROM TB_DEPARTMENT;
 -----2
SELECT DEPARTMENT_NAME||'의 정원은'||CAPACITY||'명 입니다'
FROM TB_DEPARTMENT;
-------3
SELECT STUDENT_NAME, STUDENT_NO
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NAME DESC;
 ------4
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;
-----5
SELECT PROFESSOR_NAME
FROM tb_professor
WHERE DEPARTMENT_NO IS NULL;
-----------------6
SELECT STUDENT_NAME
FROM tb_student
WHERE DEPARTMENT_NO IS NULL;
---------------7
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;
------------8
SELECT DISTINCT CATEGORY
FROM tb_department;
--------9
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '%전주%' AND
    ABSENCE_YN = 'N' AND
    EXTRACT(YEAR FROM ENTRANCE_DATE)='2002';
    
-----------------------------------------------------------------------------
--01 002학생들의 학번,이름, 입학년도 
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

-- 2이름이 세글자가 아닌 교수의 이름, 주민번호
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

-- 3남자교수들의 이름가 나이 오름차순
SELECT PROFESSOR_NAME, SUBSTR(PROFESSOR_SSN,1,2);

-- 4교수 이름 중 성을 제외한 이름만
SELECT SUBSTR(PROFESSOR_NAME,2,2)이름
FROM TB_PROFESSOR;

--5 재수생 입학자 19살에 입학하면 재수를 하지 않은것
SELECT STUENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE ;

-- 2020년 크리스마스는 무슨 요일 인가요



--7 


--8 2000이후 입학자들은 학번이A 2000이전학번 학생들의 학번, 이름조회
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT



    
    
